# Generated by Django 5.2.7 on 2025-10-11 15:08

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='code',
            field=models.CharField(default=documents.models.generate_code, max_length=4),
        ),
    ]
